# Site settings
title: Hassan Akbar
description: "Meet A Tech Monomaniac & A Travelling Freak."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://hassanakbar.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Hassan Akbar
user_title: Hassan Akbar - Software Engineer
email: hassanakbar2@gmail.com
twitter_username: Ha5SanAkbar
instagram_username: hassanakbar4
github_username:  hassanakbar
gplus_username:  HassanAkbar4
quora_username: Muhammad-Hassan-Akbar
linkedin_public_url: hassanakbar # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: https-hassanakbar-github-io
profile_picture: /assets/img/portfolio/mine.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/hassanakbar
      new_tab: true
      key_trigger: g
    - title: instagram
      url: http://www.instagram.com/hassanakbar4
      new_tab: true
      key_trigger: i
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"
#https://github.com/samikeijonen/svg-social-menu/blob/master/svg-icons.php
# projects in header index
# projects:
#   - name: AssetSonar
#     url: https://www.assetsonar.com/
#   - name: EZRentOut
#     url: https://www.ezrentout.com/
#   - name: EZOfficeInventory
#     url: https://www.ezofficeinventory.com/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
